# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "xhci_pci" "ahci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "UUID=dddae705-a616-42c5-a076-a5b4ddc315cc";
      fsType = "bcachefs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9F48-0E12";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/mnt/nasdata" =
    { device = "UUID=2653d0ea-1b79-4553-9354-8c1a6ddce06b";
      fsType = "bcachefs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/a4ec6275-8903-4a9b-9f50-f6971739c9f6"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
