# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "xhci_pci" "ahci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "UUID=c4499f64-3b7f-4429-a813-a4fe0de9f70a";
      fsType = "bcachefs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/CF1C-1929";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/mnt/nasdata" =
    { device = "UUID=3a4f9c54-266a-458e-acd2-8fc445ce0e64";
      fsType = "bcachefs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/66ccc2cf-58d5-4c05-af6e-8a56f8203f25"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
